[package]
name = "ft3_os"
version = "0.1.0"
authors = ["me <me@me.me>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
volatile = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
